In [71]:

import numpy as np
import pandas as pd

In [72]:
data=pd.read_csv("healthcare-dataset-stroke-data.csv")

In [3]:
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
id                   5110 non-null int64
gender               5110 non-null object
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
ever_married         5110 non-null object
work_type            5110 non-null object
Residence_type       5110 non-null object
avg_glucose_level    5110 non-null float64
bmi                  4909 non-null float64
smoking_status       5110 non-null object
stroke               5110 non-null int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.1+ KB

In [5]:
data["stroke"].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

In [6]:
gender=pd.get_dummies(data["gender"],drop_first=True)

In [7]:
gender["Other"].value_counts()
gender.columns

Index(['Male', 'Other'], dtype='object')

In [8]:
smoking_status=pd.get_dummies(data["smoking_status"],drop_first=True)
smoking_status

      formerly smoked  never smoked  smokes
0                   1             0       0
1                   0             1       0
2                   0             1       0
3                   0             0       1
4                   0             1       0
5                   1             0       0
6                   0             1       0
7                   0             1       0
8                   0             0       0
9                   0             0       0
10                  0             1       0
11                  0             0       1
12                  0             0       1
13                  0             0       0
14                  0             1       0
15                  0             1       0
16                  0             0       1
17                  0             0       1
18                  0             1       0
19                  0             0       0
20                  0             0       1
21                  0             1       0
22                  0             1       0
23                  0             0       0
24                  1             0       0
25                  0             1       0
26                  1             0       0
27                  0             0       0
28                  0             0       1
29                  1             0       0
...               ...           ...     ...
5080                0             1       0
5081                1             0       0
5082                0             0       1
5083                0             0       0
5084                0             0       1
5085                1             0       0
5086                0             0       0
5087                1             0       0
5088                0             0       0
5089                0             0       0
5090                0             0       1
5091                0             1       0
5092                0             1       0
5093                0             0       1
5094                0             0       0
5095                0             0       0
5096                0             1       0
5097                0             0       0
5098                0             0       0
5099                0             0       1
5100                0             1       0
5101                0             0       0
5102                0             1       0
5103                0             0       0
5104                0             0       0
5105                0             1       0
5106                0             1       0
5107                0             1       0
5108                1             0       0
5109                0             0       0

[5110 rows x 3 columns]

In [9]:
ever_married=pd.get_dummies(data["ever_married"],drop_first=True)
work_type=pd.get_dummies(data["work_type"],drop_first=True)
Residence_type=pd.get_dummies(data["Residence_type"],drop_first=True)


print(ever_married.columns)
print(work_type.columns)
print(Residence_type.columns)

Index(['Yes'], dtype='object')
Index(['Never_worked', 'Private', 'Self-employed', 'children'], dtype='object')
Index(['Urban'], dtype='object')

In [10]:
data[['Male', 'Other']]=gender

In [11]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Male,Other
0,9046,Male,67.00,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,1,0
1,51676,Female,61.00,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,0,0
2,31112,Male,80.00,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,1,0
3,60182,Female,49.00,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,0,0
4,1665,Female,79.00,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,0,0
5,56669,Male,81.00,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1,1,0
6,53882,Male,74.00,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1,1,0
7,10434,Female,69.00,0,0,No,Private,Urban,94.39,22.8,never smoked,1,0,0
8,27419,Female,59.00,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1,0,0
9,60491,Female,78.00,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1,0,0
10,12109,Female,81.00,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1,0,0
11,12095,Female,61.00,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1,0,0
12,12175,Female,54.00,0,0,Yes,Private,Urban,104.51,27.3,smokes,1,0,0
13,8213,Male,78.00,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1,1,0
14,5317,Female,79.00,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1,0,0
15,58202,Female,50.00,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1,0,0
16,56112,Male,64.00,0,1,Yes,Private,Urban,191.61,37.5,smokes,1,1,0
17,34120,Male,75.00,1,0,Yes,Private,Urban,221.29,25.8,smokes,1,1,0
18,27458,Female,60.00,0,0,No,Private,Urban,89.22,37.8,never smoked,1,0,0
19,25226,Male,57.00,0,1,No,Govt_job,Urban,217.08,NaN,Unknown,1,1,0
20,70630,Female,71.00,0,0,Yes,Govt_job,Rural,193.94,22.4,smokes,1,0,0
21,13861,Female,52.00,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1,0,0
22,68794,Female,79.00,0,0,Yes,Self-employed,Urban,228.70,26.6,never smoked,1,0,0
23,64778,Male,82.00,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1,1,0
24,4219,Male,71.00,0,0,Yes,Private,Urban,102.87,27.2,formerly smoked,1,1,0
25,70822,Male,80.00,0,0,Yes,Self-employed,Rural,104.12,23.5,never smoked,1,1,0
26,38047,Female,65.00,0,0,Yes,Private,Rural,100.98,28.2,formerly smoked,1,0,0
27,61843,Male,58.00,0,0,Yes,Private,Rural,189.84,NaN,Unknown,1,1,0
28,54827,Male,69.00,0,1,Yes,Self-employed,Urban,195.23,28.3,smokes,1,1,0
29,69160,Male,59.00,0,0,Yes,Private,Rural,211.78,NaN,formerly smoked,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,Female,29.00,0,0,Yes,Self-employed,Urban,90.52,28.0,never smoked,0,0,0
5081,37680,Male,55.00,0,0,Yes,Govt_job,Rural,108.35,40.8,formerly smoked,0,1,0
5082,24552,Female,44.00,0,0,Yes,Private,Rural,72.03,37.5,smokes,0,0,0
5083,72914,Female,19.00,0,0,No,Private,Urban,90.57,24.2,Unknown,0,0,0
5084,29540,Male,67.00,0,0,Yes,Private,Rural,97.04,26.9,smokes,0,1,0
5085,53525,Female,72.00,0,0,Yes,Private,Urban,83.89,33.1,formerly smoked,0,0,0
5086,65411,Female,51.00,0,0,Yes,Private,Urban,152.56,21.8,Unknown,0,0,0
5087,26214,Female,63.00,0,0,Yes,Self-employed,Rural,75.93,34.7,formerly smoked,0,0,0
5088,22190,Female,64.00,1,0,Yes,Self-employed,Urban,76.89,30.2,Unknown,0,0,0
5089,56714,Female,0.72,0,0,No,children,Rural,62.13,16.8,Unknown,0,0,0
5090,4211,Male,26.00,0,0,No,Govt_job,Rural,100.85,21.0,smokes,0,1,0
5091,6369,Male,59.00,1,0,Yes,Private,Rural,95.05,30.9,never smoked,0,1,0
5092,56799,Male,76.00,0,0,Yes,Govt_job,Urban,82.35,38.9,never smoked,0,1,0
5093,32235,Female,45.00,1,0,Yes,Govt_job,Rural,95.02,NaN,smokes,0,0,0
5094,28048,Male,13.00,0,0,No,children,Urban,82.38,24.3,Unknown,0,1,0
5095,68598,Male,1.08,0,0,No,children,Rural,79.15,17.4,Unknown,0,1,0
5096,41512,Male,57.00,0,0,Yes,Govt_job,Rural,76.62,28.2,never smoked,0,1,0
5097,64520,Male,68.00,0,0,Yes,Self-employed,Urban,91.68,40.8,Unknown,0,1,0
5098,579,Male,9.00,0,0,No,children,Urban,71.88,17.5,Unknown,0,1,0
5099,7293,Male,40.00,0,0,Yes,Private,Rural,83.94,NaN,smokes,0,1,0
5100,68398,Male,82.00,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0,1,0
5101,36901,Female,45.00,0,0,Yes,Private,Urban,97.95,24.5,Unknown,0,0,0
5102,45010,Female,57.00,0,0,Yes,Private,Rural,77.93,21.7,never smoked,0,0,0
5103,22127,Female,18.00,0,0,No,Private,Urban,82.85,46.9,Unknown,0,0,0
5104,14180,Female,13.00,0,0,No,children,Rural,103.08,18.6,Unknown,0,0,0
5105,18234,Female,80.00,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0,0,0
5106,44873,Female,81.00,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,0,0
5107,19723,Female,35.00,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,0,0
5108,37544,Male,51.00,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,1,0
5109,44679,Female,44.00,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,0,0

In [12]:
data[["formerly smoked","never smoked","smokes"]]=smoking_status

In [13]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Male,Other,formerly smoked,never smoked,smokes
0,9046,Male,67.00,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,1,0,1,0,0
1,51676,Female,61.00,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,0,0,0,1,0
2,31112,Male,80.00,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,1,0,0,1,0
3,60182,Female,49.00,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,0,0,0,0,1
4,1665,Female,79.00,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,0,0,0,1,0
5,56669,Male,81.00,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1,1,0,1,0,0
6,53882,Male,74.00,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1,1,0,0,1,0
7,10434,Female,69.00,0,0,No,Private,Urban,94.39,22.8,never smoked,1,0,0,0,1,0
8,27419,Female,59.00,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1,0,0,0,0,0
9,60491,Female,78.00,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1,0,0,0,0,0
10,12109,Female,81.00,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1,0,0,0,1,0
11,12095,Female,61.00,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1,0,0,0,0,1
12,12175,Female,54.00,0,0,Yes,Private,Urban,104.51,27.3,smokes,1,0,0,0,0,1
13,8213,Male,78.00,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1,1,0,0,0,0
14,5317,Female,79.00,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1,0,0,0,1,0
15,58202,Female,50.00,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1,0,0,0,1,0
16,56112,Male,64.00,0,1,Yes,Private,Urban,191.61,37.5,smokes,1,1,0,0,0,1
17,34120,Male,75.00,1,0,Yes,Private,Urban,221.29,25.8,smokes,1,1,0,0,0,1
18,27458,Female,60.00,0,0,No,Private,Urban,89.22,37.8,never smoked,1,0,0,0,1,0
19,25226,Male,57.00,0,1,No,Govt_job,Urban,217.08,NaN,Unknown,1,1,0,0,0,0
20,70630,Female,71.00,0,0,Yes,Govt_job,Rural,193.94,22.4,smokes,1,0,0,0,0,1
21,13861,Female,52.00,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1,0,0,0,1,0
22,68794,Female,79.00,0,0,Yes,Self-employed,Urban,228.70,26.6,never smoked,1,0,0,0,1,0
23,64778,Male,82.00,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1,1,0,0,0,0
24,4219,Male,71.00,0,0,Yes,Private,Urban,102.87,27.2,formerly smoked,1,1,0,1,0,0
25,70822,Male,80.00,0,0,Yes,Self-employed,Rural,104.12,23.5,never smoked,1,1,0,0,1,0
26,38047,Female,65.00,0,0,Yes,Private,Rural,100.98,28.2,formerly smoked,1,0,0,1,0,0
27,61843,Male,58.00,0,0,Yes,Private,Rural,189.84,NaN,Unknown,1,1,0,0,0,0
28,54827,Male,69.00,0,1,Yes,Self-employed,Urban,195.23,28.3,smokes,1,1,0,0,0,1
29,69160,Male,59.00,0,0,Yes,Private,Rural,211.78,NaN,formerly smoked,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,Female,29.00,0,0,Yes,Self-employed,Urban,90.52,28.0,never smoked,0,0,0,0,1,0
5081,37680,Male,55.00,0,0,Yes,Govt_job,Rural,108.35,40.8,formerly smoked,0,1,0,1,0,0
5082,24552,Female,44.00,0,0,Yes,Private,Rural,72.03,37.5,smokes,0,0,0,0,0,1
5083,72914,Female,19.00,0,0,No,Private,Urban,90.57,24.2,Unknown,0,0,0,0,0,0
5084,29540,Male,67.00,0,0,Yes,Private,Rural,97.04,26.9,smokes,0,1,0,0,0,1
5085,53525,Female,72.00,0,0,Yes,Private,Urban,83.89,33.1,formerly smoked,0,0,0,1,0,0
5086,65411,Female,51.00,0,0,Yes,Private,Urban,152.56,21.8,Unknown,0,0,0,0,0,0
5087,26214,Female,63.00,0,0,Yes,Self-employed,Rural,75.93,34.7,formerly smoked,0,0,0,1,0,0
5088,22190,Female,64.00,1,0,Yes,Self-employed,Urban,76.89,30.2,Unknown,0,0,0,0,0,0
5089,56714,Female,0.72,0,0,No,children,Rural,62.13,16.8,Unknown,0,0,0,0,0,0
5090,4211,Male,26.00,0,0,No,Govt_job,Rural,100.85,21.0,smokes,0,1,0,0,0,1
5091,6369,Male,59.00,1,0,Yes,Private,Rural,95.05,30.9,never smoked,0,1,0,0,1,0
5092,56799,Male,76.00,0,0,Yes,Govt_job,Urban,82.35,38.9,never smoked,0,1,0,0,1,0
5093,32235,Female,45.00,1,0,Yes,Govt_job,Rural,95.02,NaN,smokes,0,0,0,0,0,1
5094,28048,Male,13.00,0,0,No,children,Urban,82.38,24.3,Unknown,0,1,0,0,0,0
5095,68598,Male,1.08,0,0,No,children,Rural,79.15,17.4,Unknown,0,1,0,0,0,0
5096,41512,Male,57.00,0,0,Yes,Govt_job,Rural,76.62,28.2,never smoked,0,1,0,0,1,0
5097,64520,Male,68.00,0,0,Yes,Self-employed,Urban,91.68,40.8,Unknown,0,1,0,0,0,0
5098,579,Male,9.00,0,0,No,children,Urban,71.88,17.5,Unknown,0,1,0,0,0,0
5099,7293,Male,40.00,0,0,Yes,Private,Rural,83.94,NaN,smokes,0,1,0,0,0,1
5100,68398,Male,82.00,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0,1,0,0,1,0
5101,36901,Female,45.00,0,0,Yes,Private,Urban,97.95,24.5,Unknown,0,0,0,0,0,0
5102,45010,Female,57.00,0,0,Yes,Private,Rural,77.93,21.7,never smoked,0,0,0,0,1,0
5103,22127,Female,18.00,0,0,No,Private,Urban,82.85,46.9,Unknown,0,0,0,0,0,0
5104,14180,Female,13.00,0,0,No,children,Rural,103.08,18.6,Unknown,0,0,0,0,0,0
5105,18234,Female,80.00,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0,0,0,0,1,0
5106,44873,Female,81.00,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,0,0,0,1,0
5107,19723,Female,35.00,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,0,0,0,1,0
5108,37544,Male,51.00,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,1,0,1,0,0
5109,44679,Female,44.00,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,0,0,0,0,0

In [14]:
data[work_type.columns]=work_type
data[Residence_type.columns]=Residence_type

In [15]:
data.drop(columns=["id","gender","ever_married","work_type","Residence_type","smoking_status"],inplace=True)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 16 columns):
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
avg_glucose_level    5110 non-null float64
bmi                  4909 non-null float64
stroke               5110 non-null int64
Male                 5110 non-null uint8
Other                5110 non-null uint8
formerly smoked      5110 non-null uint8
never smoked         5110 non-null uint8
smokes               5110 non-null uint8
Never_worked         5110 non-null uint8
Private              5110 non-null uint8
Self-employed        5110 non-null uint8
children             5110 non-null uint8
Urban                5110 non-null uint8
dtypes: float64(3), int64(3), uint8(10)
memory usage: 289.5 KB

In [17]:
data["bmi"].mean()

28.893236911794673

In [18]:
data["bmi"].fillna(data["bmi"].mean(),inplace=True)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 16 columns):
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
avg_glucose_level    5110 non-null float64
bmi                  5110 non-null float64
stroke               5110 non-null int64
Male                 5110 non-null uint8
Other                5110 non-null uint8
formerly smoked      5110 non-null uint8
never smoked         5110 non-null uint8
smokes               5110 non-null uint8
Never_worked         5110 non-null uint8
Private              5110 non-null uint8
Self-employed        5110 non-null uint8
children             5110 non-null uint8
Urban                5110 non-null uint8
dtypes: float64(3), int64(3), uint8(10)
memory usage: 289.5 KB

In [20]:
pd.set_option("display.max_columns",100)

In [21]:
data

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,Male,Other,formerly smoked,never smoked,smokes,Never_worked,Private,Self-employed,children,Urban
0,67.00,0,1,228.69,36.600000,1,1,0,1,0,0,0,1,0,0,1
1,61.00,0,0,202.21,28.893237,1,0,0,0,1,0,0,0,1,0,0
2,80.00,0,1,105.92,32.500000,1,1,0,0,1,0,0,1,0,0,0
3,49.00,0,0,171.23,34.400000,1,0,0,0,0,1,0,1,0,0,1
4,79.00,1,0,174.12,24.000000,1,0,0,0,1,0,0,0,1,0,0
5,81.00,0,0,186.21,29.000000,1,1,0,1,0,0,0,1,0,0,1
6,74.00,1,1,70.09,27.400000,1,1,0,0,1,0,0,1,0,0,0
7,69.00,0,0,94.39,22.800000,1,0,0,0,1,0,0,1,0,0,1
8,59.00,0,0,76.15,28.893237,1,0,0,0,0,0,0,1,0,0,0
9,78.00,0,0,58.57,24.200000,1,0,0,0,0,0,0,1,0,0,1
10,81.00,1,0,80.43,29.700000,1,0,0,0,1,0,0,1,0,0,0
11,61.00,0,1,120.46,36.800000,1,0,0,0,0,1,0,0,0,0,0
12,54.00,0,0,104.51,27.300000,1,0,0,0,0,1,0,1,0,0,1
13,78.00,0,1,219.84,28.893237,1,1,0,0,0,0,0,1,0,0,1
14,79.00,0,1,214.09,28.200000,1,0,0,0,1,0,0,1,0,0,1
15,50.00,1,0,167.41,30.900000,1,0,0,0,1,0,0,0,1,0,0
16,64.00,0,1,191.61,37.500000,1,1,0,0,0,1,0,1,0,0,1
17,75.00,1,0,221.29,25.800000,1,1,0,0,0,1,0,1,0,0,1
18,60.00,0,0,89.22,37.800000,1,0,0,0,1,0,0,1,0,0,1
19,57.00,0,1,217.08,28.893237,1,1,0,0,0,0,0,0,0,0,1
20,71.00,0,0,193.94,22.400000,1,0,0,0,0,1,0,0,0,0,0
21,52.00,1,0,233.29,48.900000,1,0,0,0,1,0,0,0,1,0,1
22,79.00,0,0,228.70,26.600000,1,0,0,0,1,0,0,0,1,0,1
23,82.00,0,1,208.30,32.500000,1,1,0,0,0,0,0,1,0,0,0
24,71.00,0,0,102.87,27.200000,1,1,0,1,0,0,0,1,0,0,1
25,80.00,0,0,104.12,23.500000,1,1,0,0,1,0,0,0,1,0,0
26,65.00,0,0,100.98,28.200000,1,0,0,1,0,0,0,1,0,0,0
27,58.00,0,0,189.84,28.893237,1,1,0,0,0,0,0,1,0,0,0
28,69.00,0,1,195.23,28.300000,1,1,0,0,0,1,0,0,1,0,1
29,59.00,0,0,211.78,28.893237,1,1,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080,29.00,0,0,90.52,28.000000,0,0,0,0,1,0,0,0,1,0,1
5081,55.00,0,0,108.35,40.800000,0,1,0,1,0,0,0,0,0,0,0
5082,44.00,0,0,72.03,37.500000,0,0,0,0,0,1,0,1,0,0,0
5083,19.00,0,0,90.57,24.200000,0,0,0,0,0,0,0,1,0,0,1
5084,67.00,0,0,97.04,26.900000,0,1,0,0,0,1,0,1,0,0,0
5085,72.00,0,0,83.89,33.100000,0,0,0,1,0,0,0,1,0,0,1
5086,51.00,0,0,152.56,21.800000,0,0,0,0,0,0,0,1,0,0,1
5087,63.00,0,0,75.93,34.700000,0,0,0,1,0,0,0,0,1,0,0
5088,64.00,1,0,76.89,30.200000,0,0,0,0,0,0,0,0,1,0,1
5089,0.72,0,0,62.13,16.800000,0,0,0,0,0,0,0,0,0,1,0
5090,26.00,0,0,100.85,21.000000,0,1,0,0,0,1,0,0,0,0,0
5091,59.00,1,0,95.05,30.900000,0,1,0,0,1,0,0,1,0,0,0
5092,76.00,0,0,82.35,38.900000,0,1,0,0,1,0,0,0,0,0,1
5093,45.00,1,0,95.02,28.893237,0,0,0,0,0,1,0,0,0,0,0
5094,13.00,0,0,82.38,24.300000,0,1,0,0,0,0,0,0,0,1,1
5095,1.08,0,0,79.15,17.400000,0,1,0,0,0,0,0,0,0,1,0
5096,57.00,0,0,76.62,28.200000,0,1,0,0,1,0,0,0,0,0,0
5097,68.00,0,0,91.68,40.800000,0,1,0,0,0,0,0,0,1,0,1
5098,9.00,0,0,71.88,17.500000,0,1,0,0,0,0,0,0,0,1,1
5099,40.00,0,0,83.94,28.893237,0,1,0,0,0,1,0,1,0,0,0
5100,82.00,1,0,71.97,28.300000,0,1,0,0,1,0,0,0,1,0,0
5101,45.00,0,0,97.95,24.500000,0,0,0,0,0,0,0,1,0,0,1
5102,57.00,0,0,77.93,21.700000,0,0,0,0,1,0,0,1,0,0,0
5103,18.00,0,0,82.85,46.900000,0,0,0,0,0,0,0,1,0,0,1
5104,13.00,0,0,103.08,18.600000,0,0,0,0,0,0,0,0,0,1,0
5105,80.00,1,0,83.75,28.893237,0,0,0,0,1,0,0,1,0,0,1
5106,81.00,0,0,125.20,40.000000,0,0,0,0,1,0,0,0,1,0,1
5107,35.00,0,0,82.99,30.600000,0,0,0,0,1,0,0,0,1,0,0
5108,51.00,0,0,166.29,25.600000,0,1,0,1,0,0,0,1,0,0,0
5109,44.00,0,0,85.28,26.200000,0,0,0,0,0,0,0,0,0,0,1

In [22]:
Y=data["stroke"]

In [23]:
X=data.drop(columns=["stroke"])

In [24]:
Y.value_counts()

0    4861
1     249
Name: stroke, dtype: int64

In [25]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model=LogisticRegression()

In [28]:
sk=StratifiedKFold(5)

In [29]:
for i,j in sk.split(X,Y):
    print("Testing data")
    countte=0
    
    lengthte=len(Y)
    for s in Y[j]:
        if s==1:
            countte+=1
    print("1",countte)
    print("0",lengthte-countte)

    print("Training data")
    counttr=0
    lengthtr=len(Y)
    for s in Y[i]:
        if s==1:
            counttr+= 1
    print("1",counttr)
    print("0",lengthtr-counttr)

Testing data
1 50
0 5060
Training data
1 199
0 4911
Testing data
1 50
0 5060
Training data
1 199
0 4911
Testing data
1 50
0 5060
Training data
1 199
0 4911
Testing data
1 50
0 5060
Training data
1 199
0 4911
Testing data
1 49
0 5061
Training data
1 200
0 4910

In [30]:
length=50+972
one=50
zero=972
print("Testing {:.2f} % of value 1".format((one/length)*100))

Testing 4.89 % of value 1

In [31]:
onetr=199
zerotr=3889
le=onetr+zerotr
print("Training {:.2f} % of value 1".format((onetr/le)*100))

Training 4.87 % of value 1

In [43]:
model1= LogisticRegression(solver='liblinear')

In [55]:
result1=cross_val_score(model1,X,Y,cv=sk)

In [56]:
print(result1)

[0.93450635 0.93835616 0.93444227 0.94129159 0.94123408]

In [64]:
from sklearn.neighbors import KNeighborsClassifier

In [65]:
model2=KNeighborsClassifier(3)

In [66]:
result2=cross_val_score(model2,X,Y,cv=sk)
print(result2)

[0.93450635 0.93835616 0.93444227 0.94129159 0.94123408]

In [67]:
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier()

In [68]:
result3=cross_val_score(model3,X,Y,cv=sk)
print(result3)

[0.89540567 0.91878669 0.90508806 0.92563601 0.91674829]

In [74]:
print("Logistic Regression model accuracy",np.mean(result1))
print("KNN model accuracy",np.mean(result2))
print("Decision tree  model accuracy",np.mean(result3))

Logistic Regression model accuracy 0.9379660915323621
KNN model accuracy 0.9379660915323621
Decision tree  model accuracy 0.9123329437605469

In [81]:
for i,j in sk.split(X,Y):
    print

SyntaxError: unexpected EOF while parsing (<ipython-input-81-44c9f1a85728>, line 1)